/**
 * 听一听
 */
export const GET_ARTIST_LIST: string = '/artist/list' // 歌手分类列表
// export const GET_ARTIST_SUB:string = "/artist/sub" // 收藏歌手 && 取消收藏歌手
// export const GET_ARTIST_TOP_SONG:string = "/artist/top/song" // 歌手热门50首歌曲
// export const GET_ARTIST_SONGS:string = "/artist/songs" // 歌手全部歌曲
// export const GET_ARTIST_SUBLIST:string = "/artist/sublist" // 收藏的歌手列表
// export const GET_TOPIC_SUBLIST:string = "/topic/sublist" // 收藏的专栏
// export const GET_VIDEO_SUB:string = "/video/sub" // 收藏视频
// export const GET_MV_SUB:string = "/mv/sub" // 收藏MV && 取消收藏MV
// export const GET_MV_SUBLIST:string = "/mv/sublist" // 收藏的MV列表
// export const GET_PLAYLIST_CATLIST:string = "/playlist/catlist" // 歌单分类
export const GET_PLAYLIST_HOT: string = '/playlist/hot' // 热门歌单分类
export const GET_TOP_PLAYLIST: string = '/top/playlist' // 歌单(网友精选碟)
// export const GET_PLAYLIST_HIGHQUALITY_TAGS:string = "/playlist/highquality/tags" // 精品歌单标签列表
// export const GET_PLAYLIST_HIGHQUALITY:string = "/playlist/highquality" // 获取精品歌单
// export const GET_RELATED_PLAYLIST:string = "/related/playlist" // 相关歌单推荐
export const GET_PLAYLIST_DETAIL: string = '/playlist/detail' // 获取歌单详情
// export const GET_PLAYLIST_DETAIL_DYNAMIC:string = "/playlist/detail/dynamic" // 获取歌单详情动态
export const GET_SONG_URL: string = '/song/url' // 获取音乐url
export const GET_CHECK_MUSIC: string = '/check/music' // 音乐是否可用
// export const GET_SEARCH:string = "/search" // 搜索
// export const GET_CLOUDSEARCH:string = "/cloudsearch" // 搜索(更全)
// export const GET_SEARCH_DEFAULT:string = "/search/default" // 默认搜索关键词
// export const GET_SEARCH_HOT:string = "/search/hot" // 热搜列表(简略)
// export const GET_SEARCH_HOT_DETAIL:string = "/search/hot/detail" // 热搜列表(详细)
// export const GET_SEARCH_SUGGEST:string = "/search/suggest" // 搜索建议
// export const GET_SEARCH_MULTIMATCH:string = "/search/multimatch" // 搜索多重匹配
// export const GET_PLAYLIST_CREATE:string = "/playlist/create" // 新建歌单
// export const GET_PLAYLIST_DELETE:string = "/playlist/delete" // 删除歌单
// export const GET_PLAYLIST_SUBSCRIBE:string = "/playlist/subscribe" // 收藏歌单 && 取消收藏歌单
// export const GET_PLAYLIST_SUBSCRIBERS:string = "/playlist/subscribers" // 歌单收藏者
// export const GET_PLAYLIST_TRACKS:string = "/playlist/tracks" // 对歌单添加或删除歌曲
// export const GET_PLAYLIST_TRACK_ADD:string = "/playlist/track/add" // 收藏视频到视频歌单
// export const GET_PLAYLIST_TRACK_DELETE:string = "/playlist/track/delete" // 删除视频歌单里的视频
// export const GET_PLAYLIST_VIDEO_RECENT:string = "/playlist/video/recent" // 最近播放的视频
// export const GET_LYRIC:string = "/lyric" // 获取歌词
export const GET_TOP_SONG: string = '/top/song' // 新歌速递
// export const GET_HOMEPAGE_BLOCK_PAGE:string = "/homepage/block/page" // 首页发现
// export const GET_HOMEPAGE_DRAGON_BALL:string = "/homepage/dragon/ball" // 首页发现圆形图标入口列表
// export const GET_COMMENT_MUSIC:string = "/comment/music" // 歌曲评论
// export const GET_COMMENT_FLOOR:string = "/comment/floor" // 楼层评论
// export const GET_COMMENT_ALBUM:string = "/comment/album" // 专辑评论
export const GET_COMMENT_PLAYLIST: string = "/comment/playlist" // 歌单评论
// export const GET_COMMENT_MV:string = "/comment/mv" // mv评论
// export const GET_COMMENT_DJ:string = "/comment/dj" // 电台节目评论
// export const GET_COMMENT_VIDEO:string = "/comment/video" // 视频评论
// export const GET_COMMENT_HOT:string = "/comment/hot" // 热门评论
// export const GET_COMMENT_NEW:string = "/comment/new" // 新版评论接口
// export const GET_COMMENT_LIKE:string = "/comment/like" // 给评论点赞
// export const GET_HUG_COMMENT:string = "/hug/comment" // 抱一抱评论
// export const GET_COMMENT_HUG_LIST:string = "/comment/hug/list" // 评论抱一抱列表
// export const GET_COMMENT:string = "/comment" // 发送评论 && 删除评论
export const GET_HOMEPAGE_BANNER: string = '/banner' // banner
// export const GET_RESOURCE_LIKE:string = "/resource/like" // 资源点赞( MV,电台,视频)
// export const GET_PLAYLIST_MYLIKE:string = "/playlist/mylike" // 获取点赞过的视频
export const GET_SONG_DETAIL: string = '/song/detail' // 获取歌曲详情
// export const GET_ALBUM:string = "/album" // 获取专辑内容
// export const GET_ALBUM_DETAIL_DYNAMIC:string = "/album/detail/dynamic" // 专辑动态信息
// export const GET_ALBUM_SUB:string = "/album/sub" // 收藏专辑 && 取消收藏专辑
// export const GET_ALBUM_SUBLIST:string = "/album/sublist" // 获取已收藏专辑列表
// export const GET_ARTISTS:string = "/artists" // 获取歌手单曲
// export const GET_ARTISTS_MV:string = "/artists/mv" // 获取歌手mv
// export const GET_ARTISTS_ALBUM:string = "/artists/album" // 获取歌手专辑
// export const GET_ARTISTS_DESC:string = "/artists/desc" // 获取歌手描述
// export const GET_ARTISTS_DETAIL:string = "/artists/detail" // 获取歌手详情
// export const GET_SIMI_ARTISTS:string = "/simi/artist" // 获取相似歌手
// export const GET_SIMI_PLAYLIST:string = "/simi/playlist" // 获取相似歌单
// export const GET_SIMI_MV:string = "/simi/mv" // 获取相似mv
// export const GET_SIMI_SONG:string = "/simi/song" // 获取相似音乐
// export const GET_SIMI_USER:string = "/simi/user" // 获取最近5个听了这首歌的用户
// export const GET_RECOMMEND_RESOURCE:string = "/recommend/resource" // 获取每日推荐歌单
// export const GET_RECOMMEND_SONGS:string = "/recommend/songs" // 获取每日推荐歌曲
// export const GET_HISTORY_RECOMMEND_SONGS:string = "/history/recommend/songs" // 获取历史日推可用日期列表
// export const GET_HISTORY_RECOMMEND_SONGS_DETAIL:string = "/history/recommend/songs/detail" // 获取历史日推详情数据
// export const GET_PERSONALFM:string = "/personal_fm" // 私人FM
// export const GET_DAILYSIGNIN:string = "/daily_signin" // 签到
// export const GET_LIKE:string = "/like" // 喜欢音乐
// export const GET_LIKELIST:string = "/likelist" // 喜欢音乐列表
// export const GET_FMTRASH:string = "/fm_trash" // 垃圾桶
// export const GET_TOP_ALBUM:string = "/top/album" // 新碟上架
// export const GET_ALBUM_NEW:string = "/album/new" // 全部新碟
// export const GET_ALBUM_NEWEST:string = "/album/newest" // 最新专辑
// export const GET_SCROBBLE:string = "/scrobble" // 听歌打卡
// export const GET_TOP_ARTISTS:string = "/top/artists" // 热门歌手

export const GET_TOPLIST: string = '/toplist' // 所有榜单
// export const GET_TOPLIST_DETAIL:string = "/toplist/detail" // 所有榜单内容摘要
export const GET_TOPLIST_ARTIST: string = '/toplist/artist' // 歌手榜
// export const GET_USER_CLOUD:string = "/user/cloud" // 云盘
// export const GET_USER_CLOUD_DETAIL:string = "/user/cloud/detail" // 云盘数据详情
// export const GET_USER_CLOUD_DEL:string = "/user/cloud/del" // 云盘歌曲删除
// export const GET_CLOUD:string = "/cloud" // 云盘上传
// export const GET_CLOUD_MATCH:string = "/cloud/match" // 云盘歌曲信息匹配纠正

// export const GET_DJ_BANNER:string = "/dj/banner" // 电台banner
export const GET_DJ_PERSONALIZE_RECOMMEND: string = '/dj/personalize/recommend' // 电台个性推荐
// export const GET_DJ_SUBSCRIBER:string = "/dj/subscriber" // 电台订阅者列表
// export const GET_USER_AUDIO:string = "/user/audio" // 用户电台
// export const GET_USER_HOT:string = "/user/hot" // 热门电台
// export const GET_DJ_PROGRAM_TOPLIST:string = "/dj/program/toplist" // 电台节目榜
// export const GET_DJ_TOPLIST_PAY:string = "/dj/toplist/pay" // 电台付费精品
// export const GET_DJ_PROGRAM_TOPLIST_HOURS:string = "/dj/program/toplist/hours" // 电台24小时节日榜
// export const GET_DJ_TOPLIST_HOURS:string = "/dj/toplist/hours" // 电台24小时主播榜
// export const GET_DJ_TOPLIST_NEWCOMER:string = "/dj/toplist/newcomer" // 电台24小时新人榜
// export const GET_DJ_TOPLIST_POPULAR:string = "/dj/toplist/popular" // 电台最热主播榜
// export const GET_DJ_TOPLIST:string = "/dj/toplist" // 电台新晋电台榜 && 电台热门电台榜
// export const GET_RADIO_HOT:string = "/dj/radio/hot" // 类别热门电台
// export const GET_DJ_RECOMMEND:string = "/dj/recommend" // 电台推荐
// export const GET_DJ_CATELIST:string = "/dj/catelist" // 电台分类
// export const GET_DJ_RECOMMEND_TYPE:string = "/dj/recommend/type" // 电台分类推荐
// export const GET_DJ_SUB:string = "/dj/sub" // 电台订阅
// export const GET_DJ_SUBLIST:string = "/dj/sublist" // 电台订阅列表
// export const GET_DJ_PAYGIFT:string = "/dj/paygift" // 电台付费精选
// export const GET_DJ_CATEGORY_EXCLUDEHOT:string = "/dj/category/excludehot" // 电台非热门类型
// export const GET_DJ_CATEGORY_RECOMMEND:string = "/dj/category/recommend" // 电台推荐类型
// export const GET_DJ_TOADY_PERFERED:string = "/dj/today/perfered" // 电台今日优选
// export const GET_DJ_DETAIL:string = "/dj/detail" // 电台详情
// export const GET_DJ_PROGRAM:string = "/dj/program" // 电台节目
// export const GET_DJ_PROGRAM_PROGRAM:string = "/dj/program/program" // 电台节目详情
