export enum ActionTypes {
  SET_AUDIO_URL = 'SET_AUDIO_URL',
  SET_AUDIO_DETAIL = 'SET_AUDIO_DETAIL',
  SET_AUDIO_TOGGLE = 'SET_AUDIO_TOGGLE',
  SET_AUDIO_SCHEDULE = 'SET_AUDIO_SCHEDULE',
  SET_AUDIO_STATE = 'SET_AUDIO_STATE',
  SET_AUDIO_LYRIC = 'SET_AUDIO_LYRIC',
}
