export enum ActionTypes {
  SET_ACCOUNT_LOGIN = 'SET_ACCOUNT_LOGIN',
  SET_ACCOUNT_LOGOUT = 'SET_ACCOUNT_LOGOUT',
  SET_ACCOUNT_STATUS = 'SET_ACCOUNT_STATUS',
  SET_ACCOUNT_VERSION = 'SET_ACCOUNT_VERSION',
}
