export enum ActionTypes {
    SET_VIDEO_URL = "SET_VIDEO_URL",
    SET_VIDEO_DETAIL = "SET_VIDEO_DETAIL",
    SET_VIDEO_TOGGLE = "SET_VIDEO_TOGGLE",
    SET_VIDEO_SCHEDULE = "SET_VIDEO_SCHEDULE",
    SET_VIDEO_STATE = "SET_VIDEO_STATE",
    SET_VIDEO_LYRIC = "SET_VIDEO_LYRIC",
}
